### ISSUE TITLE
Panicks on empty tuples ()

### ISSUE THREAD

**Issue by perludum** [Ristarg/ronfmt#2]
Whenever there’s an empty tuple in a .ron file like this one:

```
(
    meshes: {
        "Mesh": (),
    },
)
```

ronfmt panicks with the following message:

> thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:355:21

**Comment by Ristarg** [comment]
Hi, thank you for your report.

Yes, ronfmt does not currently support empty tuples. I think making the following change in `ron.pest` should do the trick, though I'm not entirely sure:
`unit_type = { ident }` -> `unit_type = { ident | "()" }`

Sadly, I'm not currently an active Rust user, and don't even have much time for coding otherwise, so this project is not in active development anymore. Sorry about the inconvenience. I'll gladly review any patches, though.

**Comment by perludum** [comment]
Hi, thank you for your reply and for creating ronfmt!
It' a very useful and in my experience stable tool!

Looks like the grammar was correct already (tested your suggestion and several other variants), but I found a bug in ast.rs which should be resolved with https://github.com/Ristarg/ronfmt/pull/3

**Comment by Ristarg** [comment]
Just tested it, and it seems to indeed be working now. Thanks for taking the time to fix it!
